version: "3"

services:
  web:
    command: ["streamlit", "run", "app.py"]
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      ES_URL: http://elasticsearch:9200
      OPENAI_API_KEY: $OPENAI_API_KEY
      AZURE_OPENAI_API_KEY: $AZURE_OPENAI_API_KEY
      AZURE_OPENAI_API_KEY: $AZURE_OPENAI_API_KEY
    working_dir: /app
    depends_on:
      - elasticsearch
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0 # https://www.docker.elastic.co/r/elasticsearch/elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # security has been disabled, so no login or password is required.
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://localhost:9200/_cluster/health || exit 1",
        ]
      interval: 10s
      retries: 60
