# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html
[tool.black]
target-version = ["py310"]
line-length = 88

# https://pycqa.github.io/isort/docs/configuration/options.html
[tool.isort]
profile = "black"
py_version = "310"
line_length = 88
